apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: jarvice-cache-pull  
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: jarvice-cache-pull 
    spec:
      containers:
      - name: jarvice-cache-pull 
        image: ubuntu:latest
        command: [ "/bin/sh", "-c"]
        args:
            - >
                apt-get update && apt install -y jq libltdl7;
                arch=$(uname -m);
                if [ "$arch" = "x86_64" ]; then
                    arch=amd64;
                fi;
                while true; do
                    config=$(cat /etc/config/image.config);
                    images=$(( $(echo $config | jq 'length') - 1 ));
                    for image in $(seq 0 $images); do
                        echo $config | jq -r .[$image].$arch | xargs \
                                docker pull;
                    done
                    sleep ${PULL_INTERVAL}
                done
        env:
            - name: PULL_INTERVAL
              valueFrom:
                  configMapKeyRef:
                      name: image-cache
                      key: interval
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume 
          mountPath: /etc/config
        - name: docker
          mountPath: /usr/bin/docker
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: config-volume
        configMap:
          name: image-cache
      - name: docker
        hostPath:
            path: /usr/bin/docker 
      - name: docker-sock
        hostPath:
            path: /var/run/docker.sock 
